In [1]:
import numpy as np

## DataTypes & Attiributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],[4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
             [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [5]:
a1

array([1, 2, 3])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame form a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2,3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((2,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0, 10, 2)

range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size=(3,5))

random_array

array([[1, 0, 4, 1, 0],
       [6, 1, 2, 4, 0],
       [8, 1, 1, 2, 0]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
random_array_2 = np.random.random((5,3))

random_array_2

array([[0.64504234, 0.91107876, 0.32578031],
       [0.83753991, 0.1499441 , 0.07086022],
       [0.54540522, 0.73996073, 0.35915925],
       [0.61228575, 0.07928436, 0.47189541],
       [0.3587844 , 0.64302598, 0.81036586]])

In [29]:
random_array_2.shape

(5, 3)

In [30]:
random_array_3 = np.random.rand(5,3)

random_array_3

array([[0.27225381, 0.82040333, 0.42925373],
       [0.02649207, 0.99756895, 0.54499506],
       [0.40654618, 0.6399498 , 0.02572565],
       [0.57733256, 0.22483052, 0.6656115 ],
       [0.37899331, 0.17321474, 0.55243348]])

In [31]:
# Pseudo-random randoms
# By manually setting a random seed then the same random numbers are generated each time
# This is useful if you want someone who is using your code to get the same results from the same random numbers
np.random.seed(seed=99999)

random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [32]:
random_array_4.shape

(5, 3)

In [33]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices
A matrix is any array that is more than 1 dimension

In [34]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [35]:
a1

array([1, 2, 3])

In [36]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [37]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
a1[0]

1

In [39]:
a2.shape

(2, 3)

In [40]:
a2[0]

array([1. , 2. , 3.3])

In [41]:
a3.shape

(2, 3, 3)

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a3.shape

(2, 3, 3)

In [45]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [46]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [47]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [48]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [49]:
a1

array([1, 2, 3])

In [50]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [51]:
a1 + ones

array([2., 3., 4.])

In [52]:
a1 - ones

array([0., 1., 2.])

In [53]:
a1 * ones

array([1., 2., 3.])

In [54]:
a1

array([1, 2, 3])

In [55]:
a2.shape, a2.ndim

((2, 3), 2)

In [56]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [57]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [58]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [59]:
# How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"
# a2 * a3
a2_reshape = a2[:, :, np.newaxis]
a2_reshape.shape
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [60]:
a1 / ones

array([1., 2., 3.])

In [61]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [62]:
# Floor division remoes the ceimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [63]:
a2 * 2

array([[ 2. ,  4. ,  6.6],
       [ 8. , 10. , 13. ]])

In [64]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [65]:
np.add(a1, ones)

array([2., 3., 4.])

In [66]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [67]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [68]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [69]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [70]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [71]:
sum(listy_list)

6

In [72]:
sum(a1)

6

In [73]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Python dataypes and use NumPy's methods on NumPy arrays (`np.sum()`) because it's more efficient.

In [74]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [75]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [ ]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard deviation = a measure of how spread out a group of number is from the mean.
np.std(a2)

In [ ]:
# Variance = meaasure of the average degree to which each number is different to the mean.
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Standard deviation  = squareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

## Reshpaing & transposing

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2 * a3

In [ ]:
a2.reshape(2, 3, 1).shape

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)

In [ ]:
a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
a2

In [ ]:
# Transpose = switches the axis'
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3

In [ ]:
a3.T

In [ ]:
a3.T.shape

## Dot product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# Element-wise multiplication (Hardamard product)
mat1 * mat2

In [ ]:
# Dot product
np.dot(mat1, mat2)

In [ ]:
# Transpose mat1
mat1.T

In [ ]:
mat1.shape, mat2.T.shape

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

## Dot product example (nut butter sales)

In [ ]:
np.random.seed(0)

# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

In [ ]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                           index=['Mon', 'Tue', 'Wed', 'Thurs', 'Fri'],
                           columns = ['Almond butter', 'Peanut butter', 'Cashew butter'])
weekly_sales

In [ ]:
# Create prices array

prices = np.array([10, 8, 12])
prices

In [ ]:
prices.shape

In [ ]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index=['Price'],
                            columns=['Almond butter', 'Peanut butter', 'Cashew butter'])
butter_prices

In [ ]:
prices.shape

In [ ]:
sales_amounts.shape

In [ ]:
total_sales = prices.dot(sales_amounts)

In [ ]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

In [ ]:
# Create daily_sales
butter_prices.shape, weekly_sales.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
# Doesn't work, not the right shape
weekly_sales['Total ($)'] = daily_sales
weekly_sales

In [ ]:
weekly_sales['Total ($)'] = daily_sales.T
weekly_sales

### Comparison Operators

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1 > a2

In [ ]:
bool_array = a1 >= a2
bool_array

In [ ]:
type(bool_array), bool_array.dtype

In [ ]:
a1 > 5

In [ ]:
a1 < 5

In [ ]:
a1 == a1

In [ ]:
a1 == a2

## 5. Sorting Arrays

In [ ]:
random_array = np.random.randint(10, size=(3,5))
random_array

In [ ]:
random_array.shape

In [ ]:
np.sort(random_array)

In [ ]:
np.argsort(random_array)

In [ ]:
a1

In [ ]:
np.argsort(a1)

In [ ]:
np.argmin(a1)

In [ ]:
np.argmax(a1)

In [ ]:
random_array

In [ ]:
np.argmax(random_array, axis=0)

In [ ]:
np.argmax(random_array, axis=1)

## 6. Practical Example - NumPy in Action!!!

<img src='panda.png'/>

In [ ]:
# Turn an image into a NumPy array
from matplotlib.image import imread

In [ ]:
panda = imread('panda.png')
print(type(panda))

In [ ]:
panda

In [ ]:
panda.size, panda.shape, panda.ndim

In [ ]:
panda[:5]

<img src='car-photo.png'/>

In [ ]:
car = imread('car-photo.png')
print(type(car))

In [ ]:
car[:1]

<img src='dog-photo.png'/>

In [ ]:
dog = imread('dog-photo.png')
print(type(dog))

In [ ]:
dog